sudo: required
services:
    - docker

before_install:
    - docker build -t nilkeshsurana/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true nilkeshsurana/docker-react npm run test -- --coverage   