sudo: required
services:
    - docker

before_install:
    - docker build -t nilkeshsurana/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true nilkeshsurana/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-2-599115578538"