sudo: required
services:
    - docker

before_install:
    - docker build -t nilkeshsurana/docker -f Dockerfile.dev .
script:
    - docker run nilkeshsurana/docker npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-570620410534"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"